name: Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/smetankaia/decembertask .
      - run: docker push ghcr.io/smetankaia/decembertask
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 887371648
          token: 6918872876:AAGPDUxh_m10cmVRkfcy8YoXfkuaab6RNV0
          
          message: |
           Всё работает
            
            Репоп ${{github.repository}}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run ghcr.io/smetankaia/decembertask
  
